apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: testing-go-on-gh-ci 
  janus-idp.io/tekton: testing-go-on-gh-ci
  backstage.io/kubernetes-id: testing-go-on-gh-ci
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testing-go-on-gh-ci
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  