apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: testing-go-on-gh-ci-gitops
  description: This is GitOps manifest for testing-go-on-gh-ci   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: testing-go-on-gh-ci
    backstage.io/kubernetes-id: testing-go-on-gh-ci 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: lucarval-rhtap/testing-go-on-gh-ci-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:testing-go-on-gh-ci
